//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataModel.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TableCols {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableCols() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicDataModel.App_LocalResources.TableCols", typeof(TableCols).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Column_Address {
            get {
                return ResourceManager.GetString("Column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want Promotional Emails?.
        /// </summary>
        public static string Column_Allow_Prom {
            get {
                return ResourceManager.GetString("Column_Allow_Prom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Column_City {
            get {
                return ResourceManager.GetString("Column_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string Column_Contract_Type {
            get {
                return ResourceManager.GetString("Column_Contract_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Column_Country {
            get {
                return ResourceManager.GetString("Column_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string Column_Date_Add {
            get {
                return ResourceManager.GetString("Column_Date_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expires.
        /// </summary>
        public static string Column_Date_Expire {
            get {
                return ResourceManager.GetString("Column_Date_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Column_Email {
            get {
                return ResourceManager.GetString("Column_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Column_First_Name {
            get {
                return ResourceManager.GetString("Column_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Column_Floor {
            get {
                return ResourceManager.GetString("Column_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Garage?.
        /// </summary>
        public static string Column_Garage {
            get {
                return ResourceManager.GetString("Column_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Garden?.
        /// </summary>
        public static string Column_Garden {
            get {
                return ResourceManager.GetString("Column_Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a RealEstate Office?.
        /// </summary>
        public static string Column_Has_Office {
            get {
                return ResourceManager.GetString("Column_Has_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Owns a RealEstate Office.
        /// </summary>
        public static string Column_Has_Office_Desc {
            get {
                return ResourceManager.GetString("Column_Has_Office_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Column_Last_Name {
            get {
                return ResourceManager.GetString("Column_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Location.
        /// </summary>
        public static string Column_Location {
            get {
                return ResourceManager.GetString("Column_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bathrooms.
        /// </summary>
        public static string Column_Num_Bathroom {
            get {
                return ResourceManager.GetString("Column_Num_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bedrooms.
        /// </summary>
        public static string Column_Num_Bedroom {
            get {
                return ResourceManager.GetString("Column_Num_Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of floors.
        /// </summary>
        public static string Column_Num_Floors {
            get {
                return ResourceManager.GetString("Column_Num_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        public static string Column_Other {
            get {
                return ResourceManager.GetString("Column_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Column_Phone {
            get {
                return ResourceManager.GetString("Column_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Photos.
        /// </summary>
        public static string Column_Photos {
            get {
                return ResourceManager.GetString("Column_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Column_Properties {
            get {
                return ResourceManager.GetString("Column_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category.
        /// </summary>
        public static string Column_Property_Category {
            get {
                return ResourceManager.GetString("Column_Property_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Size.
        /// </summary>
        public static string Column_Property_Size {
            get {
                return ResourceManager.GetString("Column_Property_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string Column_Property_Type {
            get {
                return ResourceManager.GetString("Column_Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Price.
        /// </summary>
        public static string Column_Rent_Price {
            get {
                return ResourceManager.GetString("Column_Rent_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string Column_Sale_Price {
            get {
                return ResourceManager.GetString("Column_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want subsecribe to the Newsletter?.
        /// </summary>
        public static string Column_Sub_NewsLetter {
            get {
                return ResourceManager.GetString("Column_Sub_NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        public static string Column_Zip {
            get {
                return ResourceManager.GetString("Column_Zip", resourceCulture);
            }
        }
    }
}
