//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataModel.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TableColsDesc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableColsDesc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicDataModel.App_LocalResources.TableColsDesc", typeof(TableColsDesc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Address For Example : Mazzeh -St 1 -building 3.
        /// </summary>
        public static string Column_Address {
            get {
                return ResourceManager.GetString("Column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Adding the Property ,Today.
        /// </summary>
        public static string Column_Date_Add {
            get {
                return ResourceManager.GetString("Column_Date_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Expire Date Default 3 Months.
        /// </summary>
        public static string Column_Date_Expire {
            get {
                return ResourceManager.GetString("Column_Date_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Property Floor -1 means basment , 2 means second.
        /// </summary>
        public static string Column_Floor {
            get {
                return ResourceManager.GetString("Column_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Property Have a Garage.
        /// </summary>
        public static string Column_Garage {
            get {
                return ResourceManager.GetString("Column_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Property Have a garden.
        /// </summary>
        public static string Column_Garden {
            get {
                return ResourceManager.GetString("Column_Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number of Bathrooms.
        /// </summary>
        public static string Column_Num_Bathroom {
            get {
                return ResourceManager.GetString("Column_Num_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number of Bedrooms.
        /// </summary>
        public static string Column_Num_Bedroom {
            get {
                return ResourceManager.GetString("Column_Num_Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Number of floor the property has.
        /// </summary>
        public static string Column_Num_Floors {
            get {
                return ResourceManager.GetString("Column_Num_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is any details we didn&apos;t cover enter them here.
        /// </summary>
        public static string Column_Other {
            get {
                return ResourceManager.GetString("Column_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the property size In square meters.
        /// </summary>
        public static string Column_Property_Size {
            get {
                return ResourceManager.GetString("Column_Property_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Rent Price .
        /// </summary>
        public static string Column_Rent_Price {
            get {
                return ResourceManager.GetString("Column_Rent_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Sell Price.
        /// </summary>
        public static string Column_Sale_Price {
            get {
                return ResourceManager.GetString("Column_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Area Code if Any.
        /// </summary>
        public static string Column_Zip {
            get {
                return ResourceManager.GetString("Column_Zip", resourceCulture);
            }
        }
    }
}
