//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstrator.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Profile.
        /// </summary>
        internal static string Complete_Profile {
            get {
                return ResourceManager.GetString("Complete_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string Contact_info {
            get {
                return ResourceManager.GetString("Contact_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account..
        /// </summary>
        internal static string Control_OpenAuthProviders_SubmitTitleFormat {
            get {
                return ResourceManager.GetString("Control_OpenAuthProviders_SubmitTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        internal static string Control_OpenAuthProviders_Title {
            get {
                return ResourceManager.GetString("Control_OpenAuthProviders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string Edit_User_Details {
            get {
                return ResourceManager.GetString("Edit_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your Information.
        /// </summary>
        internal static string Edit_User_Details_Desc {
            get {
                return ResourceManager.GetString("Edit_User_Details_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Holder {
            get {
                return ResourceManager.GetString("Login_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Page_AddPhoneNumber_Name {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Page_AddPhoneNumber_PhoneNumber {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: {0}&gt;.
        /// </summary>
        internal static string Page_AddPhoneNumber_PhoneNumber_Message_YourSecurityCode {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_PhoneNumber_Message_YourSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number field is required..
        /// </summary>
        internal static string Page_AddPhoneNumber_PhoneNumber_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_PhoneNumber_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Page_AddPhoneNumber_PhoneNumber_Submit {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_PhoneNumber_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        internal static string Page_AddPhoneNumber_Title {
            get {
                return ResourceManager.GetString("Page_AddPhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Contact the Site Admin, please..
        /// </summary>
        internal static string Page_Confirm_Error {
            get {
                return ResourceManager.GetString("Page_Confirm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  here .
        /// </summary>
        internal static string Page_Confirm_Here {
            get {
                return ResourceManager.GetString("Page_Confirm_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Page_Confirm_Name {
            get {
                return ResourceManager.GetString("Page_Confirm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your account. Click.
        /// </summary>
        internal static string Page_Confirm_ThankYouPrefix {
            get {
                return ResourceManager.GetString("Page_Confirm_ThankYouPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to login.
        /// </summary>
        internal static string Page_Confirm_ThankYouSuffix {
            get {
                return ResourceManager.GetString("Page_Confirm_ThankYouSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        internal static string Page_Forgot_DisplayEmail {
            get {
                return ResourceManager.GetString("Page_Forgot_DisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Page_Forgot_Email {
            get {
                return ResourceManager.GetString("Page_Forgot_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Page_Forgot_Email_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Forgot_Email_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user either does not exist or is not confirmed..
        /// </summary>
        internal static string Page_Forgot_FailureText {
            get {
                return ResourceManager.GetString("Page_Forgot_FailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string Page_Forgot_Name {
            get {
                return ResourceManager.GetString("Page_Forgot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        internal static string Page_Forgot_Submit {
            get {
                return ResourceManager.GetString("Page_Forgot_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Page_Forgot_Title {
            get {
                return ResourceManager.GetString("Page_Forgot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        internal static string Page_Lockout_Message {
            get {
                return ResourceManager.GetString("Page_Lockout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        internal static string Page_Lockout_Name {
            get {
                return ResourceManager.GetString("Page_Lockout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Page_Login_Email {
            get {
                return ResourceManager.GetString("Page_Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Page_Login_Email_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Login_Email_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string Page_Login_Error_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Page_Login_Error_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Page_Login_ForgotPasswordHyperLink {
            get {
                return ResourceManager.GetString("Page_Login_ForgotPasswordHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Page_Login_Name {
            get {
                return ResourceManager.GetString("Page_Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New To Akaratak Sign up here!.
        /// </summary>
        internal static string Page_Login_New {
            get {
                return ResourceManager.GetString("Page_Login_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Page_Login_Password {
            get {
                return ResourceManager.GetString("Page_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Page_Login_Password_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Login_Password_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string Page_Login_RegisterHyperLink {
            get {
                return ResourceManager.GetString("Page_Login_RegisterHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string Page_Login_RememberMe {
            get {
                return ResourceManager.GetString("Page_Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Page_Login_Submit {
            get {
                return ResourceManager.GetString("Page_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in .
        /// </summary>
        internal static string Page_Login_Title {
            get {
                return ResourceManager.GetString("Page_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Page_ManageDetails_Address {
            get {
                return ResourceManager.GetString("Page_ManageDetails_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Required.
        /// </summary>
        internal static string Page_ManageDetails_Address_Required {
            get {
                return ResourceManager.GetString("Page_ManageDetails_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Page_ManageDetails_FirstName {
            get {
                return ResourceManager.GetString("Page_ManageDetails_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        internal static string Page_ManageDetails_FirstName_Required {
            get {
                return ResourceManager.GetString("Page_ManageDetails_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an Office?.
        /// </summary>
        internal static string Page_ManageDetails_HasOffice {
            get {
                return ResourceManager.GetString("Page_ManageDetails_HasOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Required.
        /// </summary>
        internal static string Page_ManageDetails_HasOffice_Required {
            get {
                return ResourceManager.GetString("Page_ManageDetails_HasOffice_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name .
        /// </summary>
        internal static string Page_ManageDetails_LastName {
            get {
                return ResourceManager.GetString("Page_ManageDetails_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        internal static string Page_ManageDetails_LastName_Required {
            get {
                return ResourceManager.GetString("Page_ManageDetails_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        internal static string Page_ManageDetails_Name {
            get {
                return ResourceManager.GetString("Page_ManageDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Page_ManageDetails_PhoneNumber {
            get {
                return ResourceManager.GetString("Page_ManageDetails_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Required.
        /// </summary>
        internal static string Page_ManageDetails_PhoneNumber_Required {
            get {
                return ResourceManager.GetString("Page_ManageDetails_PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Page_ManageDetails_Submit_Details {
            get {
                return ResourceManager.GetString("Page_ManageDetails_Submit_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        internal static string Page_ManageLogins_Name {
            get {
                return ResourceManager.GetString("Page_ManageLogins_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        internal static string Page_ManageLogins_RegisteredLogins {
            get {
                return ResourceManager.GetString("Page_ManageLogins_RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login has been removed successfuly.
        /// </summary>
        internal static string Page_ManageLogins_SuccessMessage_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Page_ManageLogins_SuccessMessage_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        internal static string Page_ManagePassword_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string Page_ManagePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string Page_ManagePassword_ConfirmNewPassword_CompareValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmNewPassword_CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password is required..
        /// </summary>
        internal static string Page_ManagePassword_ConfirmNewPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmNewPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Page_ManagePassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Page_ManagePassword_ConfirmPassword_CompareValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmPassword_CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required..
        /// </summary>
        internal static string Page_ManagePassword_ConfirmPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_ConfirmPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string Page_ManagePassword_CurrentPassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password field is required..
        /// </summary>
        internal static string Page_ManagePassword_CurrentPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_CurrentPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Password.
        /// </summary>
        internal static string Page_ManagePassword_Name {
            get {
                return ResourceManager.GetString("Page_ManagePassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Page_ManagePassword_NewPassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is required..
        /// </summary>
        internal static string Page_ManagePassword_NewPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_NewPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Page_ManagePassword_Password {
            get {
                return ResourceManager.GetString("Page_ManagePassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Page_ManagePassword_Password_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ManagePassword_Password_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local password for this site. Add a local password so you can log in without an external login..
        /// </summary>
        internal static string Page_ManagePassword_SetPassword_Text {
            get {
                return ResourceManager.GetString("Page_ManagePassword_SetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password Form.
        /// </summary>
        internal static string Page_ManagePassword_SetPassword_Title {
            get {
                return ResourceManager.GetString("Page_ManagePassword_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Page_ManagePassword_Submit_ChangePassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_Submit_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string Page_ManagePassword_Submit_SetPassword {
            get {
                return ResourceManager.GetString("Page_ManagePassword_Submit_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Details.
        /// </summary>
        internal static string Page_Manage_Details {
            get {
                return ResourceManager.GetString("Page_Manage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Page_Manage_Details_Change {
            get {
                return ResourceManager.GetString("Page_Manage_Details_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        internal static string Page_Manage_ExternalLogins {
            get {
                return ResourceManager.GetString("Page_Manage_ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        internal static string Page_Manage_Name {
            get {
                return ResourceManager.GetString("Page_Manage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Page_Manage_Password {
            get {
                return ResourceManager.GetString("Page_Manage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Change].
        /// </summary>
        internal static string Page_Manage_Password_Change {
            get {
                return ResourceManager.GetString("Page_Manage_Password_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Create].
        /// </summary>
        internal static string Page_Manage_Password_Create {
            get {
                return ResourceManager.GetString("Page_Manage_Password_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Manage].
        /// </summary>
        internal static string Page_Manage_Password_Manage {
            get {
                return ResourceManager.GetString("Page_Manage_Password_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Added Properties.
        /// </summary>
        internal static string Page_Manage_Property {
            get {
                return ResourceManager.GetString("Page_Manage_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        internal static string Page_Manage_Role {
            get {
                return ResourceManager.GetString("Page_Manage_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Page_Manage_Role_Change {
            get {
                return ResourceManager.GetString("Page_Manage_Role_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number has been added.
        /// </summary>
        internal static string Page_Manage_SuccessMessage_AddPhoneNumberSuccess {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_AddPhoneNumberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string Page_Manage_SuccessMessage_ChangePwdSuccess {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_ChangePwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        internal static string Page_Manage_SuccessMessage_RemoveLoginProvider {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_RemoveLoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was removed..
        /// </summary>
        internal static string Page_Manage_SuccessMessage_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number was removed.
        /// </summary>
        internal static string Page_Manage_SuccessMessage_RemovePhoneNumberSuccess {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_RemovePhoneNumberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        internal static string Page_Manage_SuccessMessage_SetPwdSuccess {
            get {
                return ResourceManager.GetString("Page_Manage_SuccessMessage_SetPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        internal static string Page_Manage_Title {
            get {
                return ResourceManager.GetString("Page_Manage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        internal static string Page_Manage_TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("Page_Manage_TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no two-factor authentication providers configured. See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=403804&quot;&gt;this article&lt;/a&gt;
        ///                            for details on setting up this ASP.NET application to support two-factor authentication..
        /// </summary>
        internal static string Page_Manage_TwoFactorAuthentication_NoProvider {
            get {
                return ResourceManager.GetString("Page_Manage_TwoFactorAuthentication_NoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        internal static string Page_RegisterExternalLogin_AssociationForm {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve authenticated with &lt;strong&gt;{0}&lt;/strong&gt;. Please enter an email below for the current site and click the Log in button..
        /// </summary>
        internal static string Page_RegisterExternalLogin_Description {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Page_RegisterExternalLogin_Email {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an external login.
        /// </summary>
        internal static string Page_RegisterExternalLogin_Name {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Page_RegisterExternalLogin_Submit {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with your {0} account.
        /// </summary>
        internal static string Page_RegisterExternalLogin_Title {
            get {
                return ResourceManager.GetString("Page_RegisterExternalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Page_Register_Address {
            get {
                return ResourceManager.GetString("Page_Register_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address is Required.
        /// </summary>
        internal static string Page_Register_AddressRequired {
            get {
                return ResourceManager.GetString("Page_Register_AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;By signing up you agree &lt;a href=&apos;../TermsArabic&apos;&gt;Registration Terms&lt;/a&gt; And &lt;a href=&apos;../PrivacyPolicy.aspx&apos;&gt;Privacy Policy&lt;/a&gt;.
        /// </summary>
        internal static string Page_Register_Agree {
            get {
                return ResourceManager.GetString("Page_Register_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Agree to the Terms to Continue.
        /// </summary>
        internal static string Page_Register_CheckAgree {
            get {
                return ResourceManager.GetString("Page_Register_CheckAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Page_Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Page_Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Page_Register_ConfirmPassword_CompareValidator {
            get {
                return ResourceManager.GetString("Page_Register_ConfirmPassword_CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required..
        /// </summary>
        internal static string Page_Register_ConfirmPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Register_ConfirmPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Page_Register_Email {
            get {
                return ResourceManager.GetString("Page_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Correct Email.
        /// </summary>
        internal static string Page_Register_Email_RegularExpVal {
            get {
                return ResourceManager.GetString("Page_Register_Email_RegularExpVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Page_Register_Email_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Register_Email_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Page_Register_FirstName {
            get {
                return ResourceManager.GetString("Page_Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name is Required.
        /// </summary>
        internal static string Page_Register_FirstNameRequired {
            get {
                return ResourceManager.GetString("Page_Register_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a office?.
        /// </summary>
        internal static string Page_Register_HasOffice {
            get {
                return ResourceManager.GetString("Page_Register_HasOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Page_Register_LastName {
            get {
                return ResourceManager.GetString("Page_Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name is Requred.
        /// </summary>
        internal static string Page_Register_LastNameRequired {
            get {
                return ResourceManager.GetString("Page_Register_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a member of Akaratak , Login in here .
        /// </summary>
        internal static string Page_Register_LoginLink {
            get {
                return ResourceManager.GetString("Page_Register_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Page_Register_Name {
            get {
                return ResourceManager.GetString("Page_Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Page_Register_Password {
            get {
                return ResourceManager.GetString("Page_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Page_Register_Password_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_Register_Password_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number (+963).
        /// </summary>
        internal static string Page_Register_PhoneNumber {
            get {
                return ResourceManager.GetString("Page_Register_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number is Required.
        /// </summary>
        internal static string Page_Register_PhoneNumberRequired {
            get {
                return ResourceManager.GetString("Page_Register_PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Page_Register_Submit {
            get {
                return ResourceManager.GetString("Page_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        internal static string Page_Register_Title {
            get {
                return ResourceManager.GetString("Page_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  here .
        /// </summary>
        internal static string Page_ResetPasswordConfirmation_Message_ClickHere {
            get {
                return ResourceManager.GetString("Page_ResetPasswordConfirmation_Message_ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. Click .
        /// </summary>
        internal static string Page_ResetPasswordConfirmation_Message_Prefix {
            get {
                return ResourceManager.GetString("Page_ResetPasswordConfirmation_Message_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to login.
        /// </summary>
        internal static string Page_ResetPasswordConfirmation_Message_Suffix {
            get {
                return ResourceManager.GetString("Page_ResetPasswordConfirmation_Message_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        internal static string Page_ResetPasswordConfirmation_Name {
            get {
                return ResourceManager.GetString("Page_ResetPasswordConfirmation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Page_ResetPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("Page_ResetPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Page_ResetPassword_ConfirmPassword_CompareValidator {
            get {
                return ResourceManager.GetString("Page_ResetPassword_ConfirmPassword_CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required..
        /// </summary>
        internal static string Page_ResetPassword_ConfirmPassword_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ResetPassword_ConfirmPassword_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Page_ResetPassword_Email {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Page_ResetPassword_Email_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Email_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Contact the Site Admin, please..
        /// </summary>
        internal static string Page_ResetPassword_Error {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found.
        /// </summary>
        internal static string Page_ResetPassword_Error_NoUserFound {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Error_NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Page_ResetPassword_Name {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Page_ResetPassword_Password {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Page_ResetPassword_Password_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Password_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Page_ResetPassword_Submit {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        internal static string Page_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Page_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        internal static string Page_Role_Manage_Title {
            get {
                return ResourceManager.GetString("Page_Role_Manage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Code {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Browser.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_RememberBrowser {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Submit {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Title {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_EnterVerificationCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_Error_InvalidCode {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_Error_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_Name {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Select {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Submit {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        internal static string Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Title {
            get {
                return ResourceManager.GetString("Page_TwoFactorAuthenticationSignIn_SendVerificationCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Code {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code field is required..
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Code_RequiredFieldValidator {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Code_RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone. Contact the Site Admin, please..
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Error_FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Error_FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Error_InvalidCode {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Error_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Name {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Submit {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        internal static string Page_VerifyPhoneNumber_Title {
            get {
                return ResourceManager.GetString("Page_VerifyPhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contact Info.
        /// </summary>
        internal static string Page_ViewDetails_More {
            get {
                return ResourceManager.GetString("Page_ViewDetails_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to House Details.
        /// </summary>
        internal static string Page_ViewDetail_Return {
            get {
                return ResourceManager.GetString("Page_ViewDetail_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permession {
            get {
                return ResourceManager.GetString("Permession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register_Holder {
            get {
                return ResourceManager.GetString("Register_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HouseOwner.
        /// </summary>
        internal static string Stackholder {
            get {
                return ResourceManager.GetString("Stackholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%= Resources.RealEstate.Filter_Desc_1_T %&gt;.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure?.
        /// </summary>
        internal static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that is in this role.
        /// </summary>
        internal static string User_Grantee {
            get {
                return ResourceManager.GetString("User_Grantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that is not in this role.
        /// </summary>
        internal static string User_Revoke {
            get {
                return ResourceManager.GetString("User_Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Users.
        /// </summary>
        internal static string View_Users {
            get {
                return ResourceManager.GetString("View_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
