//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class City {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal City() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.City", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allepo.
        /// </summary>
        internal static string ALPO {
            get {
                return ResourceManager.GetString("ALPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daraa.
        /// </summary>
        internal static string DARA {
            get {
                return ResourceManager.GetString("DARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damascus.
        /// </summary>
        internal static string DMCS {
            get {
                return ResourceManager.GetString("DMCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dair el zor.
        /// </summary>
        internal static string DZOR {
            get {
                return ResourceManager.GetString("DZOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edlib.
        /// </summary>
        internal static string EDLB {
            get {
                return ResourceManager.GetString("EDLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamaa.
        /// </summary>
        internal static string HAMA {
            get {
                return ResourceManager.GetString("HAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homs.
        /// </summary>
        internal static string HOMS {
            get {
                return ResourceManager.GetString("HOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latakia.
        /// </summary>
        internal static string LTKA {
            get {
                return ResourceManager.GetString("LTKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Qameshly.
        /// </summary>
        internal static string QMSY {
            get {
                return ResourceManager.GetString("QMSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rif Allepo.
        /// </summary>
        internal static string RALP {
            get {
                return ResourceManager.GetString("RALP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Raqa.
        /// </summary>
        internal static string RAQA {
            get {
                return ResourceManager.GetString("RAQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rif Damasq.
        /// </summary>
        internal static string RDMS {
            get {
                return ResourceManager.GetString("RDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Sweda.
        /// </summary>
        internal static string SWDA {
            get {
                return ResourceManager.GetString("SWDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tadmor.
        /// </summary>
        internal static string TDMR {
            get {
                return ResourceManager.GetString("TDMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tartous.
        /// </summary>
        internal static string TRTS {
            get {
                return ResourceManager.GetString("TRTS", resourceCulture);
            }
        }
    }
}
