//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DynamicData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DynamicData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Records.
        /// </summary>
        internal static string AllRecords {
            get {
                return ResourceManager.GetString("AllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home Page.
        /// </summary>
        internal static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Profile !.
        /// </summary>
        internal static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time entered in field: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string DateTime_RegularExpressionValidator_MessageFormat {
            get {
                return ResourceManager.GetString("DateTime_RegularExpressionValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date entered in field: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string Date_RegularExpressionValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Date_RegularExpressionValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date in field: [&lt;b&gt;{0}&lt;/b&gt;] is required!.
        /// </summary>
        internal static string Date_RequiredFieldValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Date_RequiredFieldValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Value at: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string Date_Validator_MessageFormat {
            get {
                return ResourceManager.GetString("Date_Validator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        internal static string Decimal_RangeValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Decimal_RangeValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal entered in field: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string Decimal_RegularExpressionValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Decimal_RegularExpressionValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        internal static string DelConfirm {
            get {
                return ResourceManager.GetString("DelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string dmmy {
            get {
                return ResourceManager.GetString("dmmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry at {0}.
        /// </summary>
        internal static string EditItemTitleFormat {
            get {
                return ResourceManager.GetString("EditItemTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Records.
        /// </summary>
        internal static string EmptyRecords {
            get {
                return ResourceManager.GetString("EmptyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while trying to add; Because of possible data duplication.
        /// </summary>
        internal static string Error_CannotAddBecauseOfDuplication {
            get {
                return ResourceManager.GetString("Error_CannotAddBecauseOfDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while trying to add. Error info:.
        /// </summary>
        internal static string Error_CannotAddWithFollowingDetails {
            get {
                return ResourceManager.GetString("Error_CannotAddWithFollowingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete because.
        /// </summary>
        internal static string Error_CannotDeleteBecauseOf {
            get {
                return ResourceManager.GetString("Error_CannotDeleteBecauseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete because of some related dependencies.
        /// </summary>
        internal static string Error_CannotDeleteBecauseOfReletedRecords {
            get {
                return ResourceManager.GetString("Error_CannotDeleteBecauseOfReletedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while trying to update. Error info:.
        /// </summary>
        internal static string Error_CannotUpdateBecauseOfDuplication {
            get {
                return ResourceManager.GetString("Error_CannotUpdateBecauseOfDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while trying to update data; Because of possible data duplication.
        /// </summary>
        internal static string Error_CannotUpdateWithFollowingDetails {
            get {
                return ResourceManager.GetString("Error_CannotUpdateWithFollowingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threre has been an error please report to the administrator.
        /// </summary>
        internal static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload &lt;b&gt;{0}&lt;/b&gt; files.
        /// </summary>
        internal static string FileUpload_ToolTip {
            get {
                return ResourceManager.GetString("FileUpload_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image(s).
        /// </summary>
        internal static string Image_Upload {
            get {
                return ResourceManager.GetString("Image_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image(s) Uploaded.
        /// </summary>
        internal static string Image_Uploaded {
            get {
                return ResourceManager.GetString("Image_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field  [&lt;b&gt;{0}&lt;/b&gt;] must be a valid integer..
        /// </summary>
        internal static string Integer_CompareValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Integer_CompareValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        internal static string Integer_RangeValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Integer_RangeValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry from {0}.
        /// </summary>
        internal static string ItemDetailsTitleFormat {
            get {
                return ResourceManager.GetString("ItemDetailsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist..
        /// </summary>
        internal static string ItemDoesNotExist {
            get {
                return ResourceManager.GetString("ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        internal static string Join_Us {
            get {
                return ResourceManager.GetString("Join_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy,rent,house,villa,mansion,details,realestate.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new entry to {0}.
        /// </summary>
        internal static string NewItemTitleFormat {
            get {
                return ResourceManager.GetString("NewItemTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        internal static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp; No Records.
        /// </summary>
        internal static string No_Records {
            get {
                return ResourceManager.GetString("No_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OF.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Text.
        /// </summary>
        internal static string PageText {
            get {
                return ResourceManager.GetString("PageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number must be Like: +123 45 6789.
        /// </summary>
        internal static string Phone_MessageFormat {
            get {
                return ResourceManager.GetString("Phone_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value Must be:.
        /// </summary>
        internal static string Range_Max_Description {
            get {
                return ResourceManager.GetString("Range_Max_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value Must be :.
        /// </summary>
        internal static string Range_Min_Description {
            get {
                return ResourceManager.GetString("Range_Min_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value entered in field: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string RegularExpressionValidator_MessageFormat {
            get {
                return ResourceManager.GetString("RegularExpressionValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: [&lt;b&gt;{0}&lt;/b&gt;] is required!.
        /// </summary>
        internal static string RequiredFieldValidator_MessageFormat {
            get {
                return ResourceManager.GetString("RequiredFieldValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Per Page.
        /// </summary>
        internal static string ResultPerPage {
            get {
                return ResourceManager.GetString("ResultPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        internal static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaratak.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Data.
        /// </summary>
        internal static string ThereIsNoData {
            get {
                return ResourceManager.GetString("ThereIsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entered in field: [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string Time_RegularExpressionValidator_MessageFormat {
            get {
                return ResourceManager.GetString("Time_RegularExpressionValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time value at field [&lt;b&gt;{0}&lt;/b&gt;] is invalid!.
        /// </summary>
        internal static string Time_Validator_MessageFormat {
            get {
                return ResourceManager.GetString("Time_Validator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update1 {
            get {
                return ResourceManager.GetString("Update1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Records.
        /// </summary>
        internal static string UpdateRecords {
            get {
                return ResourceManager.GetString("UpdateRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; is not a valid upload file type (only &lt;b&gt;{1}&lt;/b&gt; are supported)..
        /// </summary>
        internal static string UploadFile_FileTypeValidator_MessageFormat {
            get {
                return ResourceManager.GetString("UploadFile_FileTypeValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image Only.
        /// </summary>
        internal static string UploadImage_FileTypeValidator_MessageFormat {
            get {
                return ResourceManager.GetString("UploadImage_FileTypeValidator_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of validation errors.
        /// </summary>
        internal static string ValidationSummaryHeaderText {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requir Fields.
        /// </summary>
        internal static string ValRequir {
            get {
                return ResourceManager.GetString("ValRequir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No &apos;{0}&apos;].
        /// </summary>
        internal static string WhereDropdownListFilter_NullTextFormat {
            get {
                return ResourceManager.GetString("WhereDropdownListFilter_NullTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
