//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RealEstate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RealEstate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RealEstate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About our Company.
        /// </summary>
        internal static string About_Company {
            get {
                return ResourceManager.GetString("About_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property.
        /// </summary>
        internal static string Add_Property {
            get {
                return ResourceManager.GetString("Add_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Property.
        /// </summary>
        internal static string Add_Property_Desc {
            get {
                return ResourceManager.GetString("Add_Property_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Properties.
        /// </summary>
        internal static string AllRecords {
            get {
                return ResourceManager.GetString("AllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Column_Address {
            get {
                return ResourceManager.GetString("Column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Column_City {
            get {
                return ResourceManager.GetString("Column_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country first.
        /// </summary>
        internal static string Column_City_Select_First {
            get {
                return ResourceManager.GetString("Column_City_Select_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        internal static string Column_Contract_Type {
            get {
                return ResourceManager.GetString("Column_Contract_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Column_Country {
            get {
                return ResourceManager.GetString("Column_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        internal static string Column_Date_Add {
            get {
                return ResourceManager.GetString("Column_Date_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expires.
        /// </summary>
        internal static string Column_Date_Expire {
            get {
                return ResourceManager.GetString("Column_Date_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Column_Floor {
            get {
                return ResourceManager.GetString("Column_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Garage?.
        /// </summary>
        internal static string Column_Garage {
            get {
                return ResourceManager.GetString("Column_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Garden?.
        /// </summary>
        internal static string Column_Garden {
            get {
                return ResourceManager.GetString("Column_Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Location.
        /// </summary>
        internal static string Column_Location {
            get {
                return ResourceManager.GetString("Column_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bathrooms.
        /// </summary>
        internal static string Column_Num_Bathroom {
            get {
                return ResourceManager.GetString("Column_Num_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bedrooms.
        /// </summary>
        internal static string Column_Num_Bedroom {
            get {
                return ResourceManager.GetString("Column_Num_Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of floors.
        /// </summary>
        internal static string Column_Num_Floors {
            get {
                return ResourceManager.GetString("Column_Num_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        internal static string Column_Other {
            get {
                return ResourceManager.GetString("Column_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Photos.
        /// </summary>
        internal static string Column_Photos {
            get {
                return ResourceManager.GetString("Column_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Size.
        /// </summary>
        internal static string Column_Property_Size {
            get {
                return ResourceManager.GetString("Column_Property_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        internal static string Column_Property_Type {
            get {
                return ResourceManager.GetString("Column_Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Price.
        /// </summary>
        internal static string Column_Rent_Price {
            get {
                return ResourceManager.GetString("Column_Rent_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        internal static string Column_Sale_Price {
            get {
                return ResourceManager.GetString("Column_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        internal static string Column_Zip {
            get {
                return ResourceManager.GetString("Column_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commertial.
        /// </summary>
        internal static string Commertial {
            get {
                return ResourceManager.GetString("Commertial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apper Tech.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string Data_Source {
            get {
                return ResourceManager.GetString("Data_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string Delete_Item {
            get {
                return ResourceManager.GetString("Delete_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Contact.
        /// </summary>
        internal static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service Provides Direct contact between buyier and Seller  .
        /// </summary>
        internal static string Direct_Desc {
            get {
                return ResourceManager.GetString("Direct_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applyable.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feed_Back {
            get {
                return ResourceManager.GetString("Feed_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas or Suggestions?.
        /// </summary>
        internal static string Feed_Back_Desc {
            get {
                return ResourceManager.GetString("Feed_Back_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Filter Below To Customize Your Search.
        /// </summary>
        internal static string Filter_Desc_1_D {
            get {
                return ResourceManager.GetString("Filter_Desc_1_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to search for.
        /// </summary>
        internal static string Filter_Desc_1_T {
            get {
                return ResourceManager.GetString("Filter_Desc_1_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Checking the given data such as size.
        /// </summary>
        internal static string Filter_Desc_2_D {
            get {
                return ResourceManager.GetString("Filter_Desc_2_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the Property Details.
        /// </summary>
        internal static string Filter_Desc_2_T {
            get {
                return ResourceManager.GetString("Filter_Desc_2_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want more custom results.
        /// </summary>
        internal static string Filter_Desc_3_D {
            get {
                return ResourceManager.GetString("Filter_Desc_3_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More Filters.
        /// </summary>
        internal static string Filter_Desc_3_T {
            get {
                return ResourceManager.GetString("Filter_Desc_3_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basment.
        /// </summary>
        internal static string Flr_Basment {
            get {
                return ResourceManager.GetString("Flr_Basment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth Floor.
        /// </summary>
        internal static string Flr_Fifth {
            get {
                return ResourceManager.GetString("Flr_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Floor.
        /// </summary>
        internal static string Flr_First {
            get {
                return ResourceManager.GetString("Flr_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Floor.
        /// </summary>
        internal static string Flr_Fourth {
            get {
                return ResourceManager.GetString("Flr_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Floor.
        /// </summary>
        internal static string Flr_Ground {
            get {
                return ResourceManager.GetString("Flr_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Floor.
        /// </summary>
        internal static string Flr_Second {
            get {
                return ResourceManager.GetString("Flr_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Floor.
        /// </summary>
        internal static string Flr_Third {
            get {
                return ResourceManager.GetString("Flr_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 Akaratak, All Rights Reserved | &lt;a href=&quot;/About&quot; target=&quot;_blank&quot;&gt;Apper Tech&lt;/a&gt; Group.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work With Us.
        /// </summary>
        internal static string Help_Us {
            get {
                return ResourceManager.GetString("Help_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image(s).
        /// </summary>
        internal static string Image_Upload {
            get {
                return ResourceManager.GetString("Image_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image(s) Uploaded.
        /// </summary>
        internal static string Image_Uploaded {
            get {
                return ResourceManager.GetString("Image_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Join_Us {
            get {
                return ResourceManager.GetString("Join_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Information is not available.
        /// </summary>
        internal static string Map_Not_Found {
            get {
                return ResourceManager.GetString("Map_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m&lt;sup&gt;2&lt;/sup&gt;.
        /// </summary>
        internal static string MSQR {
            get {
                return ResourceManager.GetString("MSQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Property.
        /// </summary>
        internal static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Properties that match the filters.
        /// </summary>
        internal static string No_Records {
            get {
                return ResourceManager.GetString("No_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Continues Development.
        /// </summary>
        internal static string On_Develop {
            get {
                return ResourceManager.GetString("On_Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect More Services and Ideas in the Near future.
        /// </summary>
        internal static string On_Develop_Desc {
            get {
                return ResourceManager.GetString("On_Develop_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you think of our site?Any suggestions for us?.
        /// </summary>
        internal static string Opinion {
            get {
                return ResourceManager.GetString("Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Projects.
        /// </summary>
        internal static string Other_Projects {
            get {
                return ResourceManager.GetString("Other_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Properties.
        /// </summary>
        internal static string Other_Properties {
            get {
                return ResourceManager.GetString("Other_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Property Details for house ,villa, mansoin ,flat , buy or rent.
        /// </summary>
        internal static string Page_Desc_Desc {
            get {
                return ResourceManager.GetString("Page_Desc_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Details.
        /// </summary>
        internal static string Page_Details_Title {
            get {
                return ResourceManager.GetString("Page_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Property.
        /// </summary>
        internal static string Page_Edit_Title {
            get {
                return ResourceManager.GetString("Page_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can reset your Password by Clicking &lt;a href=&quot;{0}&quot;&gt;Here&lt;/a&gt;&lt;br&gt;Or Paste this URL Into the Browser&lt;br&gt;{0}.
        /// </summary>
        internal static string Page_Forget_Message_Body {
            get {
                return ResourceManager.GetString("Page_Forget_Message_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Page_Forget_Message_Title {
            get {
                return ResourceManager.GetString("Page_Forget_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property.
        /// </summary>
        internal static string Page_Insert_Title {
            get {
                return ResourceManager.GetString("Page_Insert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Properties.
        /// </summary>
        internal static string Page_ListDetails_Title {
            get {
                return ResourceManager.GetString("Page_ListDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Property.
        /// </summary>
        internal static string Page_List_Title {
            get {
                return ResourceManager.GetString("Page_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Confirm Your Email Click &lt;a href=&quot;{0}&quot;&gt;Here&lt;/a&gt;&lt;br&gt;or copy and paste this URL into the browser:&lt;br&gt;{0}.
        /// </summary>
        internal static string Page_Register_Email_Confirm_body {
            get {
                return ResourceManager.GetString("Page_Register_Email_Confirm_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm your account on Akaratak.
        /// </summary>
        internal static string Page_Register_Email_Confirm_Title {
            get {
                return ResourceManager.GetString("Page_Register_Email_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Page_User_Details_Email {
            get {
                return ResourceManager.GetString("Page_User_Details_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string Page_User_Details_Email_Send {
            get {
                return ResourceManager.GetString("Page_User_Details_Email_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address:.
        /// </summary>
        internal static string Page_User_Details_Lives_In {
            get {
                return ResourceManager.GetString("Page_User_Details_Lives_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Details.
        /// </summary>
        internal static string Page_User_Details_Name {
            get {
                return ResourceManager.GetString("Page_User_Details_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Office.
        /// </summary>
        internal static string Page_User_Details_Office {
            get {
                return ResourceManager.GetString("Page_User_Details_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownes a realestate office.
        /// </summary>
        internal static string Page_User_Details_Office_Desc {
            get {
                return ResourceManager.GetString("Page_User_Details_Office_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Page_User_Details_Phone {
            get {
                return ResourceManager.GetString("Page_User_Details_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Details.
        /// </summary>
        internal static string Page_User_Details_Title {
            get {
                return ResourceManager.GetString("Page_User_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account Details.
        /// </summary>
        internal static string Page_User_Edit {
            get {
                return ResourceManager.GetString("Page_User_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Data.
        /// </summary>
        internal static string Page_User_Insert {
            get {
                return ResourceManager.GetString("Page_User_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Info and complete profile.
        /// </summary>
        internal static string Page_User_Insert_Submit {
            get {
                return ResourceManager.GetString("Page_User_Insert_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category first.
        /// </summary>
        internal static string Property_Type_Select_First {
            get {
                return ResourceManager.GetString("Property_Type_Select_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Terms.
        /// </summary>
        internal static string Reg_Terms {
            get {
                return ResourceManager.GetString("Reg_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residental.
        /// </summary>
        internal static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Country First.
        /// </summary>
        internal static string SelectFirst {
            get {
                return ResourceManager.GetString("SelectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services For Personal and Individual Use.
        /// </summary>
        internal static string Services_Desc {
            get {
                return ResourceManager.GetString("Services_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services_Property {
            get {
                return ResourceManager.GetString("Services_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaratak.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estate is your state.
        /// </summary>
        internal static string Site_Slogan {
            get {
                return ResourceManager.GetString("Site_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Akaratak.
        /// </summary>
        internal static string Site_Welcome {
            get {
                return ResourceManager.GetString("Site_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Area.
        /// </summary>
        internal static string User_Area {
            get {
                return ResourceManager.GetString("User_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Properties.
        /// </summary>
        internal static string View_Added_Property {
            get {
                return ResourceManager.GetString("View_Added_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Properties you Added.
        /// </summary>
        internal static string View_Added_Property_Desc {
            get {
                return ResourceManager.GetString("View_Added_Property_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Properties.
        /// </summary>
        internal static string View_Property {
            get {
                return ResourceManager.GetString("View_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all available Properties.
        /// </summary>
        internal static string View_Property_Desc {
            get {
                return ResourceManager.GetString("View_Property_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Site Allows Users To add There Properties and view it.
        /// </summary>
        internal static string View_Property_Desc2 {
            get {
                return ResourceManager.GetString("View_Property_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        internal static string Villa {
            get {
                return ResourceManager.GetString("Villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaratak Find and filter Real Estate .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
